-- Segunda ronda P0. Fuentes SERMIG consultadas el 29-09-2026.
BEGIN;

UPDATE articles SET title='Declaración de infracción y PDI: pasos según tu forma de ingreso', h1='Qué hacer ante una infracción migratoria: SERMIG o PDI', meta_description='Identifica si corresponde declarar una infracción ante SERMIG o revisar tu situación con PDI. La declaración no concede residencia.', content=$h$
<h2>Primero identifica el tipo de situación</h2><p>No existe un único procedimiento de “autodenuncia” aplicable a toda irregularidad.</p><h2>Si ingresaste por un paso habilitado</h2><p>Si tu permiso venció, trabajaste sin autorización o incumpliste el plazo para solicitar la cédula, revisa la <strong>Declaración de infracción y cálculo de multa</strong> de SERMIG.</p><h2>Si eludiste el control migratorio</h2><p>La intervención de PDI puede dejar constancia e iniciar actuaciones de control. No equivale a obtener residencia y puede relacionarse con un procedimiento sancionatorio o de expulsión.</p><h2>Después de declarar</h2><p>Resolver una infracción no crea automáticamente una vía de residencia. Comprueba por separado la subcategoría, el lugar de postulación y cualquier medida administrativa pendiente.</p><p><a href="https://serviciomigraciones.cl/declarar-infraccion/" target="_blank" rel="noopener noreferrer">Revisar el trámite oficial</a>.</p>$h$, faq_items='[{"q":"¿Debo ir siempre a PDI?","a":"No. Determinadas infracciones por permiso vencido, trabajo sin autorización o retraso en solicitar la cédula se tramitan ante SERMIG."},{"q":"¿El comprobante permite trabajar?","a":"No. No reemplaza una autorización laboral."},{"q":"¿Después puedo solicitar residencia?","a":"Solo si existe una subcategoría y un lugar de postulación habilitados."}]'::jsonb, updated_at=NOW() WHERE slug='autodenuncia/pdi-paso-a-paso';

UPDATE articles SET title='PDI o SERMIG: qué autoridad corresponde', h1='PDI versus SERMIG: funciones en materia migratoria', meta_description='Diferencias entre el control migratorio de PDI y los permisos, infracciones y multas gestionados por SERMIG.', content=$h$
<h2>SERMIG</h2><p>Gestiona permisos de residencia, prórrogas, cambios, recursos y la declaración en línea de determinadas infracciones y multas.</p><h2>PDI</h2><p>Ejerce funciones de control migratorio y policía internacional. Puede intervenir en ingresos, egresos, fiscalizaciones, citaciones y elusión del control.</p><h2>Ejemplos</h2><ul><li><strong>Permiso vencido tras ingreso habilitado:</strong> SERMIG.</li><li><strong>Trabajo sin autorización:</strong> SERMIG.</li><li><strong>Solicitud o cambio de residencia:</strong> SERMIG.</li><li><strong>Ingreso por paso no habilitado o citación policial:</strong> PDI y orientación individual.</li></ul><p>Ninguna actuación ante PDI ni el pago de una multa concede por sí solo residencia.</p>$h$, faq_items='[{"q":"¿PDI concede residencias?","a":"No. Los permisos son gestionados por SERMIG."},{"q":"¿Ir a PDI garantiza regularización?","a":"No. El control o registro policial no concede residencia."}]'::jsonb, updated_at=NOW() WHERE slug='autodenuncia/sermig-vs-pdi';

UPDATE articles SET title='Permiso migratorio vencido: infracción, multa y próximos pasos', h1='Qué hacer si venció tu permiso migratorio en Chile', meta_description='Cómo declarar el vencimiento ante SERMIG, presentar descargos, pagar la multa y comprobar una posible vía posterior.', content=$h$
<h2>El vencimiento es una infracción</h2><p>Si ingresaste por un paso habilitado y permaneciste después del vencimiento, revisa la declaración de infracción y cálculo de multa de SERMIG.</p><h2>Pasos generales</h2><ol><li>Identifica el permiso y la fecha de vencimiento.</li><li>Ingresa al trámite oficial.</li><li>Revisa la causal y el cálculo.</li><li>Decide si presentarás descargos.</li><li>Paga la multa que quede firme y finaliza el trámite.</li></ol><h2>Lo que el pago no hace</h2><p>No renueva el permiso, no concede residencia, no autoriza a trabajar y no permite necesariamente presentar una primera solicitud dentro de Chile.</p><p>Si existe rechazo, abandono, expulsión, prohibición de ingreso o ingreso por paso no habilitado, busca orientación individual.</p><p><a href="https://serviciomigraciones.cl/declarar-infraccion/" target="_blank" rel="noopener noreferrer">Abrir trámite oficial</a>.</p>$h$, faq_items='[{"q":"¿Debo ir a PDI por un permiso vencido?","a":"SERMIG dispone de un trámite en línea para declarar esta infracción tras un ingreso habilitado."},{"q":"¿Pagar renueva mi permiso?","a":"No. La sanción y la residencia son procedimientos distintos."}]'::jsonb, updated_at=NOW() WHERE slug='problemas-migratorios/visa-vencida';

UPDATE articles SET title='Residencia Temporal por reciprocidad internacional', h1='Residencia Temporal por reciprocidad internacional: países y solicitud', meta_description='Países comprendidos y regla de solicitud desde el extranjero para la residencia por reciprocidad internacional.', content=$h$
<h2>Qué es</h2><p>Es una Residencia Temporal fundada en acuerdos internacionales. Debe usarse la nómina vigente de SERMIG, no una lista general de países asociados al MERCOSUR.</p><h2>Países publicados</h2><p>La ficha vigente comprende a nacionales de <strong>Argentina, Bolivia, Brasil, Paraguay y Uruguay</strong>. Pertenecer o estar asociado al MERCOSUR no basta.</p><h2>Dónde se solicita</h2><p>Se presenta <strong>desde el extranjero</strong>. Ingresar como turista no habilita a iniciar esta residencia dentro de Chile.</p><h2>Documentos</h2><p>Comprueba los requisitos vigentes de identidad, antecedentes, vigencia y legalización directamente en la ficha oficial.</p><p><a href="https://serviciomigraciones.cl/residencia-temporal/subcategorias/" target="_blank" rel="noopener noreferrer">Consultar la nómina oficial</a>.</p>$h$, faq_items='[{"q":"¿Puedo solicitarla desde Chile como turista?","a":"No. Se presenta desde el extranjero."},{"q":"¿Colombia, Ecuador o Perú están incluidos?","a":"No aparecen en la nómina vigente de esta subcategoría publicada por SERMIG."},{"q":"¿Necesito contrato?","a":"El fundamento es la nacionalidad comprendida, pero debes cumplir los demás requisitos."}]'::jsonb, updated_at=NOW() WHERE slug='residencia-temporal/mercosur';

UPDATE articles SET title='Cambio de subcategoría de Residencia Temporal', h1='Cómo cambiar de subcategoría o calidad de Residencia Temporal', meta_description='Quién puede solicitar el cambio, cuándo presentarlo y qué documentos exige SERMIG.', content=$h$
<h2>Quién puede solicitarlo</h2><p>Está dirigido a personas que <strong>ya poseen Residencia Temporal</strong>: titulares que quieren cambiar de subcategoría o dependientes que desean cambiar su calidad. No transforma turismo o Permanencia Transitoria en residencia.</p><h2>Dónde se solicita</h2><p>Se presenta dentro de Chile en el portal de SERMIG.</p><h2>Cuándo</h2><p>SERMIG indica que debe solicitarse antes del vencimiento de los plazos para pedir la prórroga, con no más de 90 días de anticipación respecto del vencimiento.</p><h2>Requisitos</h2><p>Debes acreditar la residencia vigente y cumplir los requisitos generales y específicos de la nueva subcategoría.</p><p><a href="https://serviciomigraciones.cl/residencia-temporal/cambio-de-subcategoria-o-calidad/" target="_blank" rel="noopener noreferrer">Consultar el trámite oficial</a>.</p>$h$, faq_items='[{"q":"¿Puedo cambiar de turista a residente?","a":"No. Este trámite es para quienes ya poseen Residencia Temporal."},{"q":"¿Se solicita desde Chile?","a":"Sí, por titulares o dependientes de Residencia Temporal que cumplen los requisitos."},{"q":"¿Puedo hacerlo en cualquier momento?","a":"SERMIG fija una oportunidad vinculada al vencimiento; revisa la fecha oficial."}]'::jsonb, updated_at=NOW() WHERE slug='residencia-temporal/cambio-categoria';

COMMIT;
